### ISSUE TITLE
The SDK cannot be minified

### ISSUE THREAD

**Issue by mr-tichyt** [Orange-OpenSource/OCast-JS#5]
In function.helpers.ts is the following code:

```
   /** Return list of parameters for function pass in params
     * @param {function} func
     * @returns {string} - Modified String
     * @private
     */
    public static getParamNames(func): string[] {
        const fnStr = func.toString().replace(FunctionHelper.STRIP_COMMENTS, "");
        let result = fnStr.slice(fnStr.indexOf("(") + 1, fnStr.indexOf(")")).match(FunctionHelper.ARGUMENT_NAMES);
        if (result === null) {
            result = [];
        }
        return result;
    }
```

It is used for validation of all required prams of a remote call. The problem is, that when the source code is minified - which it usually is for production usage - the param names get changed to be shorter. That breaks the validation because the new names does not match with the names in the message.

Anyways, the stringification of function and extracting its param names is very uncommon and "unclean" and I would strongly suggest not to do that.

Thank you very much,
Tomas

**Comment by delphin-germa-orange** [comment]
Hi @mr-tichyt 
I've changed mapping between messages and methods with annotations to keep real names parameters during execution. It's more clean and in the future we will able to check params types, ...
